{% set name = "docstring_parser_fork" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/docstring_parser_fork-{{ version }}.tar.gz
  sha256: 95b23cc5092af85080c716a6da68360f5ae4fcffa75f4a3aca5e539783cbcc3d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0

test:
  imports:
    - docstring_parser
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jsh9/docstring_parser_fork
  summary: Parse Python docstrings in reST, Google and Numpydoc format
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
