{% set name = "docstring_parser_fork" %}
{% set version = "0.0.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/docstring_parser_fork-{{ version }}.tar.gz
  sha256: a2743a63d8d36c09650594f7b4ab5b2758fee8629dcf794d1b221b23179baa5c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.0

test:
  imports:
    - docstring_parser
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jsh9/docstring_parser_fork
  summary: Parse Python docstrings in reST, Google and Numpydoc format
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
